name: Run Test

on:
  pull_request:
    paths:
      - wacruit/**
      - .github/workflows/test.yaml

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: test-user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root-password
          MYSQL_DATABASE: testdb
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      env: test

    steps:
      - uses: actions/checkout@v3

      - name: change mysql charset
        run: mysql -h 127.0.0.1 -P 3307 -u root -p'root-password' -e "ALTER DATABASE testdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: 3.11
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/wacruit/
          uv run pytest --junit-xml=${GITHUB_WORKSPACE}/wacruit/test.xml ./

      - name: Test reports
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: backend tests
          path: "./wacruit/test.xml"
          reporter: java-junit

      # run pre-commit only different from base branch
      # it contains pylint, black, isort, etc.
      - name: Run pre-commit
        run: |
          git fetch origin ${{ github.base_ref }}
          uv run pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD

      - name: Run alembic migration test
        run: |
          mkdir -p wacruit/src/database/migrations/versions
          ls wacruit/src/database/migrations/versions/* || uv run alembic revision --autogenerate
          uv run alembic upgrade head
